- name: Ensure yum-utils is installed.
  yum: pkg=yum-utils state=latest
- name: Ensure python-selinux is installed on all nodes.
  yum: pkg=libselinux-python state=latest
- name: Set SELinux to permissive
  action: selinux policy=targeted state=permissive
- name: Install EPEL repository
  yum: pkg=epel-release state=latest
- name: Download and enable the Remi repository definitions
  shell: rpm -Uvh --replacepkgs http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#- name: Download and enable the rpmforge repository definitions
#  shell: rpm -Uvh --replacepkgs http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
- name: Set proper timezone
  shell: sudo timedatectl set-timezone Europe/Rome
- name: Install Python PIP
  yum: pkg=python-pip state=latest
- name: Install Net Tools
  yum: pkg=net-tools state=latest
- name: Install boto via PIP
  pip: name=boto state=latest
- name: Install GIT
  yum: pkg=git state=latest
- name: Install VIM
  yum: pkg=vim state=latest
- name: Install wget
  yum: pkg=wget state=latest
- name: Install htop
  yum: pkg=htop state=latest
- name: Install zip
  yum: pkg=zip state=latest
- name: Install unzip
  yum: pkg=unzip state=latest
- name: Install telnet
  yum: pkg=telnet state=latest
- name: Install GCC
  yum: pkg=gcc state=latest
- name: Install NTP
  yum: pkg=ntp state=latest
- name: Ensure that NTP is running
  service: name=ntpd state=started
- name: Set NTP as a startup item
  shell: systemctl enable ntpd
- name: Enable swap file
  shell: /bin/dd if=/dev/zero of=/swapfile bs=1M count=1024 && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && sh -c 'echo "/swapfile none swap sw 0 0" >> /etc/fstab'
  args:
    creates: /swapfile